<?php
$form = $this->form;
$form->prepare();
?>
<?php echo $this->form()->openTag($form->setAttribute('class','form-horizontal'));?>

    <?php echo $this->formText($form->get('id')); ?>

    <div class="form-group">
        <div class="col-sm-9 col-lg-10">
            <?php echo $this->formText($form->get('qq')->setAttribute('placeholder','QQ号')); ?>
            @<?php echo $this->formText($form->get('domain')->setAttribute('value','qq.com')); ?>
        </div>
    </div>
    
    <div class="form-group">
        <div class="col-sm-offset-3 col-sm-9 col-lg-offset-2 col-lg-10">
        <?php echo $this->formSubmit($form->get('submit')->setAttributes(array(
            'value' => '添加'
        ))); ?>
        </div>
    </div>

<?php echo $this->form()->closeTag(); ?>