<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'Console\Module'                        => __DIR__ . '/Module.php',
    'Console\Controller\IndexController' => __DIR__ . '/src/Console/Controller/IndexController.php',
    'ConsoleTest\Framework\TestCase'        => __DIR__ . '/tests/Console/Framework/TestCase.php',
    'ConsoleTest\SampleTest'                => __DIR__ . '/tests/Console/SampleTest.php',
);
