<a href="<?php echo $this->url('console/task_edit'); ?>">添加任务</a>

<?php if (count($this->paginator)): ?>
<ul>
<?php foreach ($this->paginator as $item): ?>
  <li><a href="<?php echo $this->url('console/task_edit',array('task_id'=>$item->id)); ?>"><?=$item->title; ?></a> <a href="<?php echo $this->url('console/queue',array('task_id'=>$item->id)); ?>">查看任务详情</a></li>
<?php endforeach; ?>
</ul>
<?php endif; ?>

<?php echo $this->paginationControl($this->paginator,
                                    'Sliding',
                                    'widget/pagination-control', array('route' => 'console/default', 'routeParams' => array(
                                        'controller' => 'task'
))); ?>
