<a href="<?php echo $this->url('console/queue_edit',array('task_id'=>$task_id)); ?>">添加队列项</a>

<?php if (count($this->paginator)): ?>
<ul>
<?php foreach ($this->paginator as $item): ?>
  <li><?php print_r($item); ?></li>
<?php endforeach; ?>
</ul>
<?php endif; ?>

<?php echo $this->paginationControl($this->paginator,
                                    'Sliding',
                                    'widget/pagination-control', array('route' => 'console/queue', 'routeParams' => array(
                                        'task_id' => $task_id,
))); ?>